[package]
name = "openai"
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true

[dependencies]
openai_api_rust = { workspace = true }
